# From GIT ID: [1f5c79b]
esphome:
  name: bedroomlights
  platform: ESP8266
  board: esp12e
  on_boot:
    then:
      - light.turn_on:
          id: light_panel_light
          brightness: 25%

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bedroomlights Fallback Hotspot"
    password: !secret fallback_ap_pass

  # manual_ip:
    # static_ip: 192.168.0.102
    # gateway: 192.168.0.1
    # subnet: 255.255.255.0

captive_portal:

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  password: !secret api_pass

ota:
  password: !secret ota_pass

i2c:
  sda: GPIO4
  scl: GPIO5
  scan: False
    
output:
  - platform: template
    id: dimmer_bedroom
    type: float
    min_power: 0.2
    write_action:
      - i2c.write: !lambda |-
            auto val = (byte)(int)(state * 100);
            return { 0x6A, 0x00, val };
  - platform: esp8266_pwm
    id: panel_light
    pin: GPIO15

light:
  - platform: monochromatic
    output: dimmer_bedroom
    id: bedroom_light
    name: "Bedroom Light"
    gamma_correct: 2.2
  - platform: monochromatic
    name: "Bedroom Panel LED"
    output: panel_light
    id: light_panel_light
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
      inverted: True
    internal: True
    name: "Touch Bedroom Light"
    id: binary_sensor_bedroom
    on_multi_click:
    - timing:
        - ON for at most 1s
        - OFF for at most 1s
        - ON for at least 1s
      then:
        - logger.log: "Touch Bedroom Light Double Clicked Long"
        - while:
            condition:
              binary_sensor.is_on: binary_sensor_bedroom
            then:
              - light.dim_relative:
                  id: bedroom_light
                  relative_brightness: -5%
                  transition_length: 0.2s
              - delay: 0.2s
    - timing:
        - ON for at least 1s
      then:
        - logger.log: "Touch Bedroom Light Single Clicked Long"
        - while:
            condition:
              binary_sensor.is_on: binary_sensor_bedroom
            then:
              - light.dim_relative:
                  id: bedroom_light
                  relative_brightness: 5%
                  transition_length: 0.2s
              - delay: 0.2s
    - timing:
        - ON for at most 1s
        - OFF for at least 0.3s
      then:
        - logger.log: "Touch Bedroom Light Single Clicked Short"
        - light.toggle: bedroom_light
  - platform: gpio
    pin:
      number: GPIO2
      mode: INPUT_PULLUP
      inverted: True
    internal: True
    name: "Touch External Light"
    id: binary_sensor_external
    on_multi_click:
    - timing:
        - ON for at most 1s
        - OFF for at most 1s
        - ON for at least 1s
      then:
        - logger.log: "Touch External Light Double Clicked Long"
        - while:
            condition:
              binary_sensor.is_on: binary_sensor_external
            then:
              - homeassistant.service:
                  service: light.dim_relative
                  data:
                    entity_id: light.high_light
                    relative_brightness: -5%
                    transition_length: 0.2s
              - delay: 0.2s
    - timing:
        - ON for at least 1s
      then:
        - logger.log: "Touch External Light Single Clicked Long"
        - while:
            condition:
              binary_sensor.is_on: binary_sensor_external
            then:
              - homeassistant.service:
                  service: light.dim_relative
                  data:
                    entity_id: light.high_light
                    relative_brightness: 5%
                    transition_length: 0.2s
              - delay: 0.2s
    - timing:
        - ON for at most 1s
        - OFF for at least 0.3s
      then:
        - logger.log: "Touch External Light Single Clicked Short"
        - homeassistant.service:
            service: light.toggle
            data:
              entity_id: light.high_light