esphome:
  name: fishpondswitch
  platform: ESP8266
  board: esp12e
#  arduino_version: espressif8266@2.2.3
  on_boot:
    then:
      - switch.turn_on:
          id: switch_fishpond_pump
      - switch.turn_on:
          id: switch_fishpond_light

wifi:
  ssid: !secret wifi_ssid_2
  password: !secret wifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fishpondswitch Fallback Hotspot"
    password: !secret fallback_ap_pass

  # manual_ip:
    # static_ip: 192.168.0.104
    # gateway: 192.168.0.1
    # subnet: 255.255.255.0

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_pass

ota:
  password: !secret ota_pass

switch:
  - platform: gpio
    id: switch_fishpond_pump
    name: "Fishpond Pump"
    pin: GPIO12
  - platform: gpio
    id: switch_fishpond_light
    name: "Fishpond UV Light"
    pin: GPIO14
    
binary_sensor:
  - platform: gpio
    id: button_fishpond_pump
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: True
    internal: True
    on_state:
      - switch.toggle: switch_fishpond_pump