esphome:
  name: fountainswitch
  platform: ESP8266
  board: esp12e
#  arduino_version: espressif8266@2.2.3
  # on_boot:
    # then:
      # - switch.turn_off:
          # id: switch_fountain

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fountainswitch Fallback Hotspot"
    password: !secret fallback_ap_pass

  # manual_ip:
    # static_ip: 192.168.0.104
    # gateway: 192.168.0.1
    # subnet: 255.255.255.0

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_pass

ota:
  password: !secret ota_pass

switch:
  - platform: gpio
    id: switch_fountain
    name: "Fountain"
    pin: GPIO4
    
binary_sensor:
  - platform: gpio
    id: button_fountain
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: True
    internal: True
    on_state:
      - switch.toggle: switch_fountain