substitutions:
  # device config
  device_name: gate
  platform: ESP8266
  board: esp12e

  # cover config
  open_duration: "13400" # ms
  close_duration: "13400" # ms
  cover_device_class: gate

  # switch config
  gate_trigger_pin: GPIO13 # gpio pin that trigger the gate opening/closing/stop
  gate_trigger_pulse_duration: 400ms # amount of time gate_trigger_pin is pulsed for
  $push_interval: "1500" # safe time between relay activations in ms

  # endstop config
  open_endstop_pin: GPIO12 # gpio pin for open endstop sensor
  close_endstop_pin: GPIO14 # gpio pin for close endstop sensor
  debounce_time: 30ms # debounce time for open/close endstops

  # addons (water meter)
  reed_switch_pin: GPIO5

packages:
  common: !include common/config_base.yaml
  wifi: !include common/wifi_base.yaml
  device_base: !include common/gate_base.yaml
  device_addons: !include common/water_meter_base.yaml


# Enable logging
logger:
  level: DEBUG
  # level: DEBUG

#debug switch for logging
# switch:
#   - platform: template
#     name: "log it"
#     id: log_it
#     lambda: !lambda |-
#       return true;
#     turn_on_action:
#       - lambda: !lambda |-
#           ESP_LOGD("log_it", "LOG CO:%u PO:%f LD:%u", id(garage_door).current_operation,  id(garage_door).position, id(last_dir));
#     turn_off_action:
#       - lambda: !lambda |-
#           ESP_LOGD("log_it", "LOG CO:%u PO:%f LD:%u", id(garage_door).current_operation,  id(garage_door).position, id(last_dir));