esphome:
  name: loungelamp
  platform: ESP8266
  board: esp12e

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lounge Lamp Fallback Hotspot"
    password: !secret fallback_ap_pass

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_pass

ota:
  password: !secret ota_pass
  
binary_sensor:
  - platform: gpio
    id: button_lounge_lamp
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: True
    internal: True
    on_state:
      - light.toggle: light_lounge_lamp

output:
  - platform: gpio
    id: output_lounge_lamp
    pin: GPIO12

light:
  - platform: binary
    id: light_lounge_lamp
    name: "Lamp"
    output: output_lounge_lamp