wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $device_name Fallback Hotspot
    password: !secret fallback_ap_pass

captive_portal:

# Enable Home Assistant API
api:
  password: !secret api_pass

ota:
  password: !secret ota_pass
